channels: # Keep empty since we are using a Harmony v7 output
channelid:
    1: OrigBrightfield
    2: OrigER
    3: OrigAGP
    4: OrigMito
    5: OrigDNA
    6: OrigRNA
metadata:
    Row: Row
    Col: Col
    FieldID: FieldID
    PlaneID: PlaneID
    ChannelID: ChannelID
    PositionX: PositionX
    PositionY: PositionY
    PositionZ: PositionZ
    AbsPositionZ: AbsPositionZ
